INSERT INTO MOVIE (MOVIE_TITLE, DIRECTOR, PRICE) VALUES ('Movie1', 'Director1', 25);
INSERT INTO MOVIE (MOVIE_TITLE, DIRECTOR, PRICE) VALUES ('Movie2', 'Director2', 49);
INSERT INTO MOVIE (MOVIE_TITLE, DIRECTOR, PRICE) VALUES ('Movie3', 'Director3', 15);
INSERT INTO MOVIE (MOVIE_TITLE, DIRECTOR, PRICE) VALUES ('Movie4', 'Director4', 10);
INSERT INTO MOVIE (MOVIE_TITLE, DIRECTOR, PRICE) VALUES ('Movie5', 'Director5', 45);
INSERT INTO MOVIE (MOVIE_TITLE, DIRECTOR, PRICE) VALUES ('Movie6', 'Director6', 25);
INSERT INTO MOVIE (MOVIE_TITLE, DIRECTOR, PRICE) VALUES ('Movie7', 'Director7', 55);
INSERT INTO MOVIE (MOVIE_TITLE, DIRECTOR, PRICE) VALUES ('Movie8', 'Director8', 40);

