INSERT INTO DIRECTOR(NAME) VALUES ('Director1');
INSERT INTO DIRECTOR(NAME) VALUES ('Director2');
INSERT INTO DIRECTOR(NAME) VALUES ('Director3');
INSERT INTO DIRECTOR(NAME) VALUES ('Director4');
INSERT INTO DIRECTOR(NAME) VALUES ('Director5');
INSERT INTO DIRECTOR(NAME) VALUES ('Director6');
INSERT INTO DIRECTOR(NAME) VALUES ('Director7');
INSERT INTO DIRECTOR(NAME) VALUES ('Director8');

INSERT INTO MOVIE (MOVIE_TITLE, PRICE, DIRECTOR_ID) VALUES ('Movie1', 25, 1);
INSERT INTO MOVIE (MOVIE_TITLE, PRICE, DIRECTOR_ID) VALUES ('Movie2', 49, 2);
INSERT INTO MOVIE (MOVIE_TITLE, PRICE, DIRECTOR_ID) VALUES ('Movie3', 15, 3);
INSERT INTO MOVIE (MOVIE_TITLE, PRICE, DIRECTOR_ID) VALUES ('Movie4', 10, 4);
INSERT INTO MOVIE (MOVIE_TITLE, PRICE, DIRECTOR_ID) VALUES ('Movie5', 45, 5);
INSERT INTO MOVIE (MOVIE_TITLE, PRICE, DIRECTOR_ID) VALUES ('Movie6', 25, 6);
INSERT INTO MOVIE (MOVIE_TITLE, PRICE, DIRECTOR_ID) VALUES ('Movie7', 55, 7);
INSERT INTO MOVIE (MOVIE_TITLE, PRICE, DIRECTOR_ID) VALUES ('Movie8', 40, 8);

select * from movie;